### ISSUE TITLE
修改 console 文案

### ISSUE THREAD

**Issue by wnxn** [QingCloudAppcenter/QKE#97]
- [x] 审计日志文件输出地点说明，在/etc/kubernetes/audit/audit-log-file #109 
https://github.com/QingCloudAppcenter/QKE/blob/5a0d08e05a3767e38719307511596e19d086dcc1/app/config/config.json#L499 
- [x] 审计日志文件说明，用户要确保文件在 QKE master 上是存在的。 #109 
- [x] registry mirror 提示1个空格分割。#135

**Comment by wnxn** [comment]
- [ ] registry mirror 提示1个空格分割
